CREATE TABLE IF NOT EXISTS CIRCLES
(
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL UNIQUE,
    PRICE INTEGER NOT NULL
    );

CREATE TABLE IF NOT EXISTS LEARNERS
(
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    LAST_NAME VARCHAR(30) NOT NULL,
    FIRST_NAME VARCHAR(30) NOT NULL,
    CLASS INTEGER NOT NULL,
    CIRCLE_ID INTEGER REFERENCES CIRCLES(ID)

    CONSTRAINT CLASS_CHECK CHECK ( CLASS <= 11 )
    );